### ISSUE TITLE
Tasks' indices are not updated properly when they are reloaded from the json file

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#67]
Try modifying the tasks' indices in the file then use the gui to delete tasks, the storage will run into errors

**Comment by bihuutue** [comment]
To replicate bug: edit task A's index to be the same as task B's. Reopen the program. When command delete task A, task B will be deleted instead.
Reason: task A's index now points to the position of task B. Resulting in deletion of Task B. 
Solution options: (b is currently applied)
a) put in the manual the requirement of user not editing the indices. (cost 0)
b) check the task whether the index is replicated in the taskList, if yes, return error message! (cost O(n))
C) we change to passing the task instead of its index, then search and delete that task (cost O(n))
