### ISSUE TITLE
Display some suggested autocomplete words as users are typing

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#90]
You can use the getSuggestion API and pass in a maximum number of suggested words to be 5 for examples

**Comment by ndt93** [comment]
I just test this. There is a small problem in which the suggestion is called without the last character which is just typed in. A possible solution is to append the key captured in the key event to the text gotten by .getText() method.

**Comment by ndt93** [comment]
Also you may want to call the version of getSuggestions with the maxWords specified for improved performance

**Comment by sharminelow** [comment]
I have set the max number of words to 5. Originally, I was thinking of having gui query the current screen size, and decide the MAX_LENGTH displayed on the status string instead of 40. Because if you resize, status string will be cut off. Now it think it can be left to later. 

The key pressed also needs to handle backspace, so I have to check before I append. I will try to fix the last character issue in a better way when i can compile with my eclipse =(

**Comment by ndt93** [comment]
Haha don't worry :). These are some small details. Just take your time to fix the append character thing
